### ISSUE TITLE
frozen dict doesn't support recursive

### ISSUE THREAD

**Issue by dawncold** [zelaznik/frozen_dict#1]
I found the top level dict type is `frozen_dict.FrozenDict`, but if one element is a `dict`, `frozen_dict.FrozenDict` will not process it, just keep it original type

**Comment by zelaznik** [comment]
Can you send me the code or a screenshot?

Steve Zelaznik
410.375.8414
Sent from either an
iPhone or an Android

**Comment by dawncold** [comment]
@zelaznik 
![screenshot from 2015-06-09 21 17 46](https://cloud.githubusercontent.com/assets/502856/8058593/0af8a786-0eed-11e5-9b91-995d811bc907.png)

I init FrozenDict instance with a dict, but the inner dict `d1` also the `dict` type and I can modify `d1`

**Comment by zelaznik** [comment]
That's by design.  It's not recursively frozen.  The only thing that's frozen are the key-value pairs.  The values themselves can be mutable in the same way that a tuple can contain a list,

**Comment by dawncold** [comment]
Thanks @zelaznik 

Actually, we write a frozendict in project, and it will recursively frozen, but when we init it, large deepcopy operation we think makes slow, is there any fast way to deepcopy one dict to another? the buffer protocol in python is available for dict?

**Comment by zelaznik** [comment]
You can give this recursive function a shot.  I don't know if it's any faster than deepcopy, but I imagine with your project you're deep copying every time you create a new thread.

Let me know if this helps.

    def freeze(obj):
        try:
            #See if the object is hashable
            hash(obj)
            return obj
        except TypeError:
            pass
            
        try:
            #Try to see if this is a mapping
            frz = {k: freeze(obj[k]) for k in obj}
            return FrozenDict(frz)
        except TypeError:
            pass
            
        # See if the object is a set like
        # or sequence like object
        try:
            obj[0]
            cls = tuple
        except TypeError:
            cls = frozenset
        except IndexError:
            cls = tuple
        
        return cls(map(freeze, obj))

**Comment by zelaznik** [comment]
I might put this into a separate Python file, but I caught a rare case in the previous version where [0,1,2,3,4] would accidentally be converted into FrozenDict({0:0, 1:1, 2:2, 3:3, 4:4}).  Here's the new code.  Again this is NOT unit tested, so there may be more errors, but this is a starting point.  If you can make this more robust, I'd be happy to add a recursively frozen feature into the next version of FrozenDict.

    def freeze(obj):
        try:
            #See if the object is hashable
            hash(obj)
            return obj
        except TypeError:
            pass
            
        try:
            #Try to see if this is a mapping
            try:
                obj[tuple(obj)]
            except KeyError:
                pass
            frz = {k: freeze(obj[k]) for k in obj}
            return FrozenDict(frz)
        except TypeError:
            pass
            
        # See if the object is a set like
        # or sequence like object
        try:
            obj[0]
            cls = tuple
        except TypeError:
            cls = frozenset
        except IndexError:
            cls = tuple
        
        return cls(freeze(i) for i in obj)

**Comment by dawncold** [comment]
hi @zelaznik it's almost faster than our freeze func, but we have some hashable object, like `Entity`, it's the dict subclass with implemented `__hash__` func.

why not freeze hashable object?

**Comment by zelaznik** [comment]
Because if "Entity" isn't already frozen it shouldn't be returning a hash in the first place.
